from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MonitorSystem.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    url(r'^.*static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_PATH}),
    url(r'^index', 'ShareMethod.views.index'),
    url(r'^SuccessMessage', 'ShareMethod.views.SuccessMessage'),
    url(r'^FailureMessage', 'ShareMethod.views.FailureMessage'),
    url(r'^login$', 'Login.views.login'),
    url(r'^login2', 'Login.views.login2'),
    url(r'^logout$', 'Login.views.logout'),
    url(r'^NoticeInfo/select', 'NoticeInfo.views.select'),
    url(r'^MonitorInfo/select', 'MonitorInfo.views.select'),
    url(r'^MonitorInfo/insert', 'MonitorInfo.views.insert'),
    url(r'^MonitorInfo/update', 'MonitorInfo.views.update'),
    url(r'^MonitorInfo/modify', 'MonitorInfo.views.modify'),
    url(r'^MonitorInfo/delete', 'MonitorInfo.views.delete'),
    url(r'^MonitorInfo/ServerConfig', 'MonitorInfo.views.ServerConfig'),
    url(r'^ServerInfo/select', 'ServerInfo.views.select'),
    url(r'^ServerInfo/insert', 'ServerInfo.views.insert'),
    url(r'^ServerInfo/update', 'ServerInfo.views.update'),
    url(r'^ServerInfo/modify', 'ServerInfo.views.modify'),
    url(r'^ServerInfo/delete', 'ServerInfo.views.delete'),
    url(r'^UserInfo/insert', 'UserInfo.views.insert'),
    url(r'^UserInfo/select', 'UserInfo.views.select'),
    url(r'^UserInfo/modify', 'UserInfo.views.modify'),
    url(r'^UserInfo/update', 'UserInfo.views.update'),
    url(r'^UserGroup/select', 'UserGroup.views.select'),
    url(r'^UserGroup/insert', 'UserGroup.views.insert'),
    url(r'^UserGroup/modify', 'UserGroup.views.modify'),
    url(r'^UserGroup/update', 'UserGroup.views.update'),
    url(r'^ServerManager/select', 'ServerManager.views.select'),
    url(r'^ServerManager/insert', 'ServerManager.views.insert'),
    url(r'^ServerManager/modify', 'ServerManager.views.modify'),
    url(r'^ServerManager/update', 'ServerManager.views.update'),
    url(r'^ServerInfo/CommandConfig', 'ServerInfo.views.CommandConfig'),
    url(r'^ServerMonitorInfo/select', 'ServerMonitorInfo.views.select'),
    url(r'^ServerMonitorInfo/insert', 'ServerMonitorInfo.views.insert'),
    url(r'^ServerMonitorInfo/update', 'ServerMonitorInfo.views.update'),
    url(r'^ServerMonitorInfo/modify', 'ServerMonitorInfo.views.modify'),
    url(r'^ServerMonitorInfo/delete', 'ServerMonitorInfo.views.delete'),
    url(r'^AdminUser/select', 'AdminUser.views.select'),
    url(r'^AdminUser/insert', 'AdminUser.views.insert'),
    url(r'^AdminUser/update', 'AdminUser.views.update'),
    url(r'^AdminUser/modify', 'AdminUser.views.modify'),
    url(r'^CommentList/select', 'CommentList.views.select'),
    url(r'^CommentList/insert', 'CommentList.views.insert'),
    url(r'^CommentList/update', 'CommentList.views.update'),
    url(r'^CommentList/modify', 'CommentList.views.modify'),
    url(r'^HttpMonitor/select', 'HttpMonitor.views.select'),
    url(r'^HttpMonitor/insert', 'HttpMonitor.views.insert'),
    url(r'^HttpMonitor/update', 'HttpMonitor.views.update'),
    url(r'^HttpMonitor/modify', 'HttpMonitor.views.modify'),
    url(r'^MonitorPort/select', 'MonitorPort.views.select'),
    url(r'^MonitorPort/insert', 'MonitorPort.views.insert'),
    url(r'^MonitorPort/update', 'MonitorPort.views.update'),
    url(r'^MonitorPort/modify', 'MonitorPort.views.modify'),
    url(r'^ServerManager/select', 'ServerManager.views.select'),
    url(r'^ServerManager/insert', 'ServerManager.views.insert'),
    url(r'^ServerManager/update', 'ServerManager.views.update'),
    url(r'^ServerManager/modify', 'ServerManager.views.modify'),
    url(r'^ServerManager/delete', 'ServerManager.views.delete'),
    url(r'^TableBackup/select', 'TableBackup.views.select'),
    url(r'^TableBackup/insert', 'TableBackup.views.insert'),
    url(r'^TableBackup/update', 'TableBackup.views.update'),
    url(r'^TableBackup/modify', 'TableBackup.views.modify'),
    url(r'^TableBackup/delete', 'TableBackup.views.delete'),
    url(r'^ConfigInfo/select', 'ConfigInfo.views.select'),
    url(r'^ConfigInfo/update', 'ConfigInfo.views.update'),
    url(r'^ConfigInfo/modify', 'ConfigInfo.views.modify'),
    
    
)
