from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ProvincesTest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    url(r'^.*static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_PATH}),
    url(r'^index', 'ShareMethod.views.index'),
    url(r'^SuccessMessage', 'ShareMethod.views.SuccessMessage'),
    url(r'^FailureMessage', 'ShareMethod.views.FailureMessage'),
    url(r'^login$', 'Login.views.login'),
    url(r'^logout$', 'Login.views.logout'),
    url(r'^PhoneCard/select_un', 'PhoneCard.views.select_un'),
    url(r'^PhoneCard/select_cm', 'PhoneCard.views.select_cm'),
    url(r'^PhoneCard/select_cdma.do$', 'PhoneCard.views.select_cdma'),
    url(r'^PhoneCard/select_cdma1.do$', 'PhoneCard.views.select_cdma1'),
    url(r'^OutBox/insert_un', 'OutBox.views.insert_un'),
    url(r'^OutBox/insert_cm', 'OutBox.views.insert_cm'),
    url(r'^OutBox/insert_cdma.do$', 'OutBox.views.insert_cdma'),
    url(r'^OutBox/insert_cdma1.do$', 'OutBox.views.insert1_cdma'),
    url(r'^ServiceSmsInfo/insert_un', 'ServiceSmsInfo.views.insert_un'),
    url(r'^ServiceSmsInfo/insert_cm', 'ServiceSmsInfo.views.insert_cm'),
    url(r'^ServiceSmsInfo/insert_cdma.do', 'ServiceSmsInfo.views.insert_cdma'),
    url(r'^ServiceSmsInfo/insert_cdma1.do', 'ServiceSmsInfo.views.insert_cdma1'),
    url(r'^DeliverQuery/select_auto_un', 'DeliverQuery.views.select_auto_un'),
    url(r'^DeliverQuery/select_auto_cm', 'DeliverQuery.views.select_auto_cm'),
    url(r'^DeliverQuery/select_auto_cdma', 'DeliverQuery.views.select_auto_cdma'),
    url(r'^DeliverQuery/select_un', 'DeliverQuery.views.select_un'),
    url(r'^DeliverQuery/select_cm', 'DeliverQuery.views.select_cm'),
    url(r'^DeliverQuery/select_cdma.do$', 'DeliverQuery.views.select_cdma'),
    url(r'^DeliverQuery/select_cdma1.do$', 'DeliverQuery.views.select_cdma1'),
    url(r'^TestStatistics/selectMt_un', 'TestStatistics.views.selectMt_un'),
    url(r'^TestStatistics/selectMt_cm', 'TestStatistics.views.selectMt_cm'),
    url(r'^TestStatistics/selectMt_cdma.do', 'TestStatistics.views.selectMt_cdma'),
    url(r'^TestStatistics/selectMt_cdma1.do', 'TestStatistics.views.selectMt_cdma1'),
    url(r'^TestStatistics/selectMo_un', 'TestStatistics.views.selectMo_un'),
    url(r'^TestStatistics/selectMo_cm', 'TestStatistics.views.selectMo_cm'),
    url(r'^TestStatistics/selectMo_cdma.do', 'TestStatistics.views.selectMo_cdma'),
    url(r'^TestStatistics/selectMo_cdma1.do', 'TestStatistics.views.selectMo_cdma1'),
    url(r'^SendQuery/select_un', 'SendQuery.views.select_un'),
    url(r'^SendQuery/select_cm', 'SendQuery.views.select_cm'),
    url(r'^SendQuery/select_cdma.do$', 'SendQuery.views.select_cdma'),
    url(r'^SendQuery/select_cdma1.do$', 'SendQuery.views.select_cdma1'),
    url(r'^SendQuery/select_auto_un', 'SendQuery.views.select_auto_un'),
    url(r'^SendQuery/select_auto_cm', 'SendQuery.views.select_auto_cm'),
    url(r'^SendQuery/select_auto_cdma', 'SendQuery.views.select_auto_cdma'),
    url(r'^AutoSendConfig/insert', 'AutoSendConfig.views.insert'),
    url(r'^AutoSendConfig/select', 'AutoSendConfig.views.select'),
    url(r'^AutoSendConfig/update', 'AutoSendConfig.views.update'),
    url(r'^AutoSendConfig/modify', 'AutoSendConfig.views.modify'),
    url(r'^AutoSendConfig/delete', 'AutoSendConfig.views.delete'),
)
